theme: jekyll-theme-minimal
title: DocJungle
description: >
  FPGA-Group@Trusted Cloud Lab, <br>
  Shanghai Jiaotong University<br>
    <br>
  Zhengwei Qi : qizhwei@sjtu.edu.cn<br>
  Yanqiang Liu : oai@sjtu.edu.cn<br>
  Yongbiao Chen : chenyongbiao0319@sjtu.edu.cn<br>
  KaiChen Guo : guoKaicheng@sjtu.edu.cn<br>
  Cheng'gang Wu : wuchenggang@sjtu.edu.cn<br>
  Kaishi Li : lee_cash@126.com<br>
  Yinjie Zhang : 2673274393@qq.com
