theme: jekyll-theme-minimal
title: DocJ
description: Zhengwei Qi : qizhwei@sjtu.edu.cn\<br>Yanqiang Liu : oai@sjtu.edu.cn\<br>Yongbiao Chen : ,KaiChen Guo : ,Chen'gang Wu : ,Kaishi Li : lee_cash@126.com,Yinjie Zhang :
